version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 10
            nvm alias default 10
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v10-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v10-dependencies-
      - run:
          name: Install dependencies
          command: |
            source ~/.nvm/nvm.sh
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v10-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build and compile
          command: |
            source ~/.nvm/nvm.sh
            npm run build
      - run:
          name: Run tests
          command: |
            source ~/.nvm/nvm.sh
            ./start-test-env.sh
            npm test
      - run:
          name: Lint files
          command: |
            source ~/.nvm/nvm.sh
            npm run lint
      - run:
          name: Upload code coverage
          command: |
            source ~/.nvm/nvm.sh
            npx codecov
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
